import { Trade, TradeTag } from "./types";

export const mockTrades: Trade[] = [
  {
    id: "1",
    user_id: "demo",
    date: "2026-03-12",
    trade_number: 1,
    symbol: "AAPL",
    strategy: "Breakout Long",
    entry_price: 178.50,
    stop_price: 176.20,
    target_price: 183.00,
    followed_rules: true,
    result_r: 2.1,
    mood_score: 4,
    intent_notes: "Clean breakout above resistance with volume confirmation.",
    status: "closed",
    before_screenshot_url: null,
    after_screenshot_url: null,
    created_at: "2026-03-12T09:30:00Z",
    updated_at: "2026-03-12T15:00:00Z",
  },
  {
    id: "2",
    user_id: "demo",
    date: "2026-03-12",
    trade_number: 2,
    symbol: "TSLA",
    strategy: "Mean Reversion",
    entry_price: 245.00,
    stop_price: 248.00,
    target_price: 238.00,
    followed_rules: false,
    result_r: -1.0,
    mood_score: 2,
    intent_notes: "Entered too early, didn't wait for confirmation candle.",
    status: "closed",
    before_screenshot_url: null,
    after_screenshot_url: null,
    created_at: "2026-03-12T10:15:00Z",
    updated_at: "2026-03-12T14:30:00Z",
  },
  {
    id: "3",
    user_id: "demo",
    date: "2026-03-11",
    trade_number: 1,
    symbol: "NVDA",
    strategy: "Flag Pattern",
    entry_price: 890.00,
    stop_price: 882.00,
    target_price: 910.00,
    followed_rules: true,
    result_r: 1.5,
    mood_score: 5,
    intent_notes: "Perfect flag on 5m chart. Waited for pullback.",
    status: "closed",
    before_screenshot_url: null,
    after_screenshot_url: null,
    created_at: "2026-03-11T09:45:00Z",
    updated_at: "2026-03-11T13:00:00Z",
  },
  {
    id: "4",
    user_id: "demo",
    date: "2026-03-11",
    trade_number: 2,
    symbol: "SPY",
    strategy: "Gap Fill",
    entry_price: 512.30,
    stop_price: 510.50,
    target_price: 515.00,
    followed_rules: true,
    result_r: 0.8,
    mood_score: 3,
    intent_notes: "Gap fill play, hit partial target.",
    status: "closed",
    before_screenshot_url: null,
    after_screenshot_url: null,
    created_at: "2026-03-11T10:00:00Z",
    updated_at: "2026-03-11T12:00:00Z",
  },
  {
    id: "5",
    user_id: "demo",
    date: "2026-03-12",
    trade_number: 3,
    symbol: "META",
    strategy: "VWAP Bounce",
    entry_price: null,
    stop_price: null,
    target_price: null,
    followed_rules: true,
    result_r: null,
    mood_score: 4,
    intent_notes: "Watching for VWAP bounce at 520 level. Pre-market plan logged.",
    status: "open",
    before_screenshot_url: null,
    after_screenshot_url: null,
    created_at: "2026-03-12T08:00:00Z",
    updated_at: "2026-03-12T08:00:00Z",
  },
];

export const mockTradeTags: TradeTag[] = [
  { id: "t1", trade_id: "1", tag: "Rule-Based" },
  { id: "t2", trade_id: "1", tag: "Breakout" },
  { id: "t3", trade_id: "2", tag: "FOMO" },
  { id: "t4", trade_id: "2", tag: "Late Entry" },
  { id: "t5", trade_id: "3", tag: "Rule-Based" },
  { id: "t6", trade_id: "3", tag: "A+ Setup" },
  { id: "t7", trade_id: "4", tag: "Rule-Based" },
  { id: "t8", trade_id: "5", tag: "Rule-Based" },
];
