// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ymoyzfvtcoxoculwneor.supabase.co";
const SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inltb3l6ZnZ0Y294b2N1bHduZW9yIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzMzMDY4MDUsImV4cCI6MjA4ODg4MjgwNX0.VzkEj1ALKUj0bTOfY8nl0aM1La6wKjjJgFRQHnIHHNc";
// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_ANON_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
